# Generated by Django 5.1.6 on 2025-02-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medication',
            field=models.CharField(default='not_chosen', max_length=100),
        ),
    ]
