# Generated by Django 5.1.6 on 2025-02-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medication',
            field=models.CharField(default='not chosen', max_length=100),
        ),
    ]
