# Generated by Django 5.1.6 on 2025-02-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_times_taken_per_day_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='medication',
        ),
        migrations.AddField(
            model_name='profile',
            name='medication',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.medication'),
        ),
    ]
