# Generated by Django 5.1.6 on 2025-02-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_medication_profile_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dosage',
            field=models.IntegerField(default=0),
        ),
    ]
