# Generated by Django 5.1.6 on 2025-03-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='day_number',
            field=models.IntegerField(default=0),
        ),
    ]
