# Generated by Django 5.1.6 on 2025-03-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_journal_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='mood',
            field=models.CharField(choices=[('Improving', 'Improving'), ('Stable', 'Stable'), ('Worsening', 'Worsening')], default='Stable', max_length=50),
        ),
    ]
