# Generated by Django 5.1.6 on 2025-03-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_journal_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='remembered',
            field=models.BooleanField(default=False),
        ),
    ]
