# Generated by Django 5.1.6 on 2025-03-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_journal_remembered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='remembered',
            new_name='remembered_medication',
        ),
    ]
