# Generated by Django 5.1.6 on 2025-03-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_remembered_journal_remembered_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='remembered_medication',
            new_name='remembered',
        ),
    ]
