# Generated by Django 5.1.6 on 2025-03-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_journal_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='content',
            new_name='notes',
        ),
    ]
